set_property SRC_FILE_INFO {cfile:C:/Users/ruyuan/Desktop/FPGA_Design-master/Lab06/xdc_v2/pynq-z2_v1.0.xdc rfile:../../../../../xdc_v2/pynq-z2_v1.0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { clk }]; #IO_L13P_T2_MRCC_35 Sch=sysclk
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { clk }];
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/mem_i_i_1_n_0]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/cmd_done]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[0]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[1]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[2]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[3]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[4]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[5]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[6]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[7]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[0]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[1]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[2]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[3]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[4]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[5]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[6]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[7]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[0]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[1]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[2]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[3]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[4]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[5]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[6]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[7]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[0]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[1]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[2]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[3]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[4]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[5]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[6]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[7]}]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[0]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[1]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[2]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[3]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[4]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[5]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[6]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[7]}]]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[0]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[1]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[2]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[3]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[4]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[5]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[6]} {system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[7]}]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/cmd_done]]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/mem_i_i_1_n_0]]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[2]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[0]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[2]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[5]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/mem_i_i_1_n_0]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[1]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[3]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[29]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[30]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[8]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[22]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[1]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[7]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[3]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/rst]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[26]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[4]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[5]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[10]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[11]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[28]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[31]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[23]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[17]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[4]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[27]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[0]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[6]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[7]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[13]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[14]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[19]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[24]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[12]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[6]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[3]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/clk_4_f]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[0]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[1]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[21]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[2]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[9]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[15]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[16]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[18]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[20]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[25]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[0]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[1]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[2]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[3]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[4]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[5]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[6]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/address[7]}]]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[0]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[1]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[2]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_in_to_mem[3]}]]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[0]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[1]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[2]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[3]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[4]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[5]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[6]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[7]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[8]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[9]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[10]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[11]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[12]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[13]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[14]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[15]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[16]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[17]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[18]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[19]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[20]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[21]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[22]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[23]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[24]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[25]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[26]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[27]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[28]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[29]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[30]} {design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/data_out[31]}]]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/clk_4_f]]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/mem_i_i_1_n_0]]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/bram_0/inst/bram_v1_0_S00_AXI_inst/m_ctrl1/rst]]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
